version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: api_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin_
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Admin_

volumes:
  pgdata:
